bazel_dep(name = "rules_bazelrio", version = "")
bazel_dep(name = "bzlmodrio-allwpilib", version = "2026.1.1")
bazel_dep(name = "rules_bzlmodrio_toolchains", version = "2025-1.bcr5")
bazel_dep(name = "rules_jvm_external", version = "6.8")
bazel_dep(name = "rules_cc", version = "0.2.13")
bazel_dep(name = "rules_wpi_styleguide", version = "2025.06.22")
bazel_dep(name = "rules_checkstyle", version = "10.12.2.bcr1")
bazel_dep(name = "rules_pmd", version = "7.2.0.bcr1")
bazel_dep(name = "rules_spotless", version = "2.40.0.bcr1")
bazel_dep(name = "rules_wpiformat", version = "2026.57")
bazel_dep(name = "rules_bzlmodrio_jdk", version = "17.0.12-7.bcr1")

local_path_override(
    module_name = "rules_bazelrio",
    path = "..",
)

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "org.junit.jupiter:junit-jupiter-api:5.10.1",
        "org.junit.jupiter:junit-jupiter-params:5.10.1",
        "org.junit.jupiter:junit-jupiter-engine:5.10.1",
        "org.junit.platform:junit-platform-commons:1.6.1",
        "org.junit.platform:junit-platform-console:1.6.1",
        "org.junit.platform:junit-platform-engine:1.6.1",
        "org.junit.platform:junit-platform-launcher:1.6.1",
        "org.junit.platform:junit-platform-suite-api:1.6.1",
    ],
    repositories = [
        "https://repo1.maven.org/maven2",
        "https://frcmaven.wpi.edu/artifactory/release/",
    ],
)
use_repo(
    maven,
    "maven",
)
