load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "rules_bazelrio",
    path = "..",
)

http_archive(
    name = "rules_java",
    sha256 = "1558508fc6c348d7f99477bd21681e5746936f15f0436b5f4233e30832a590f9",
    url = "https://github.com/bazelbuild/rules_java/releases/download/8.12.0/rules_java-8.12.0.tar.gz",
)

http_archive(
    name = "rules_jvm_external",
    sha256 = "c18a69d784bcd851be95897ca0eca0b57dc86bb02e62402f15736df44160eb02",
    strip_prefix = "rules_jvm_external-6.3",
    url = "https://github.com/bazelbuild/rules_jvm_external/releases/download/6.3/rules_jvm_external-6.3.tar.gz",
)

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

BZLMODRIO_COMMITISH = "e40f601b09f412686eb8f08d0e465ba3f90130cc"

BZLMODRIO_SHA256 = "67c66263f1198e31e491739ca0f0b2796f9024d94ee41d70da25997cf0590f6e"

http_archive(
    name = "bzlmodrio",
    sha256 = BZLMODRIO_SHA256,
    strip_prefix = "bzlmodRio-{}".format(BZLMODRIO_COMMITISH),
    url = "https://github.com/bzlmodRio/bzlmodRio/archive/{}.tar.gz".format(BZLMODRIO_COMMITISH),
)

load("@bzlmodrio//private/non_bzlmod:download_dependencies.bzl", "download_dependencies")

download_dependencies(
    allwpilib_version = "2025.1.1",
    pathplannerlib_version = None,
    phoenix_version = None,
    photonlib_version = None,
    revlib_version = None,
    rules_bazelrio_version = None,
    # ni_version = None,
    # opencv_version = None,
    # apriltaglib_version = None,
    # imgui_version = None,
    # libssh_version = None,
    studica_version = None,
    # rules_pmd_version = None,
    # rules_spotless_version = None,
    # rules_wpi_styleguide_version = None,
    # rules_toolchains_version = None,
    # rules_checkstyle_version = None,
)

load("@bzlmodrio//private/non_bzlmod:setup_dependencies.bzl", "get_java_dependencies", "setup_dependencies")
load("@rules_jvm_external//:defs.bzl", "maven_install")

setup_dependencies()

maven_artifacts, maven_repositories = get_java_dependencies()

maven_install(
    name = "maven",
    artifacts = maven_artifacts + [],
    repositories = maven_repositories,
    # maven_install_json = "//build_scripts/bazel/deps:maven_install.json",
)

#####################
# Styleguide
#####################

load("@rules_wpi_styleguide//dependencies:load_rule_dependencies.bzl", "load_styleguide_rule_dependencies")

load_styleguide_rule_dependencies()

load("@rules_wpi_styleguide//dependencies:load_dependencies.bzl", "load_styleguide_dependencies")

load_styleguide_dependencies()

load("@rules_wpi_styleguide//dependencies:load_transitive_dependencies.bzl", "load_styleguide_transitive_dependencies")

load_styleguide_transitive_dependencies()

load("@rules_wpi_styleguide//dependencies:setup_styleguide.bzl", "setup_styleguide")

setup_styleguide()

load("@rules_wpi_styleguide//dependencies:load_pins.bzl", "load_styleguide_pins")

load_styleguide_pins()
#####################

http_archive(
    name = "rules_bzlmodrio_jdk",
    integrity = "sha256-CuS7x85kbqJ7k3gC8Bae5BWgCd/SHRogBXd8jJ/d7+k=",
    strip_prefix = "rules_bzlmodrio_jdk-002eda2bf3dcb98c68aa6ab7b6d8c30112b7892e",
    urls = [
        "https://github.com/bzlmodRio/rules_bzlmodrio_jdk/archive/002eda2bf3dcb98c68aa6ab7b6d8c30112b7892e.zip",
    ],
)

load("@rules_bzlmodrio_jdk//:maven_deps.bzl", "setup_legacy_setup_jdk_dependencies")

setup_legacy_setup_jdk_dependencies()
