load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

local_repository(
    name = "rules_bazelrio",
    path = "..",
)

http_archive(
    name = "rules_java",
    sha256 = "",
    url = "https://github.com/bazelbuild/rules_java/releases/download/7.1.0/rules_java-7.1.0.tar.gz",
)

http_archive(
    name = "rules_jvm_external",
    sha256 = "d31e369b854322ca5098ea12c69d7175ded971435e55c18dd9dd5f29cc5249ac",
    strip_prefix = "rules_jvm_external-5.3",
    url = "https://github.com/bazelbuild/rules_jvm_external/releases/download/5.3/rules_jvm_external-5.3.tar.gz",
)

load("@rules_jvm_external//:repositories.bzl", "rules_jvm_external_deps")

rules_jvm_external_deps()

BZLMODRIO_COMMITISH = "77dae7eabf1517ea58cf90d854f7d9d5a81561e6"

BZLMODRIO_SHA256 = "9e62b75600a972cee1bafdb6fc8d43be0690db496c421cebf2c9376d92f564e5"

http_archive(
    name = "bzlmodrio",
    sha256 = BZLMODRIO_SHA256,
    strip_prefix = "bzlmodRio-{}".format(BZLMODRIO_COMMITISH),
    url = "https://github.com/bzlmodRio/bzlmodRio/archive/{}.tar.gz".format(BZLMODRIO_COMMITISH),
)

load("@bzlmodrio//private/non_bzlmod:download_dependencies.bzl", "download_dependencies")

download_dependencies(
    allwpilib_version = "2024.1.1-beta-1",
    # ni_version = None,
    # opencv_version = None,
    apriltaglib_version = None,
    imgui_version = None,
    libssh_version = None,
    navx_version = None,
    pathplannerlib_version = None,
    phoenix_version = None,
    photonlib_version = None,
    revlib_version = None,
    rules_bazelrio_version = None,
    rules_checkstyle_version = None,
    rules_pmd_version = None,
    rules_spotless_version = None,
    # rules_toolchains_version = None,
    rules_wpi_styleguide_version = None,
)

load("@bzlmodrio//private/non_bzlmod:setup_dependencies.bzl", "get_java_dependencies", "setup_dependencies")
load("@rules_jvm_external//:defs.bzl", "maven_install")

setup_dependencies()

maven_artifacts, maven_repositories = get_java_dependencies()

maven_install(
    name = "maven",
    artifacts = maven_artifacts + [],
    repositories = maven_repositories,
    # maven_install_json = "//build_scripts/bazel/deps:maven_install.json",
)
