name: Build example project
on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build_native:
    strategy:
      fail-fast: false
      matrix:
        include:
        # Build bzlmod, native
        - { name: "windows - bzlmod native", os: windows-latest, command: "build",  config: "", bazel_options: "--output_user_root=C:\\bazelroot", }
        - { name: "ubuntu  - bzlmod native", os: ubuntu-latest,  command: "build",  config: "", bazel_options: "",                                 }
        - { name: "macos   - bzlmod native", os: macos-latest,   command: "build",  config: "", bazel_options: "",                                 }

        # Build non-bzlmod, native
        - { name: "windows - bzlmod native", os: windows-latest, command: "build",  config: "--noenable_bzlmod", bazel_options: "--output_user_root=C:\\bazelroot", }
        - { name: "ubuntu  - bzlmod native", os: ubuntu-latest,  command: "build",  config: "--noenable_bzlmod", bazel_options: "",                                 }
        - { name: "macos   - bzlmod native", os: macos-latest,   command: "build",  config: "--noenable_bzlmod", bazel_options: "",                                 }

    name: "Build - ${{ matrix.name }}"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - run: bazel ${{ matrix.bazel_options }} build -k ${{ matrix.config }} --verbose_failures --enable_bzlmod //...
